### PR TITLE
Update to include configuration of feedPollDelay property

### PR DESCRIPTION
**Pull request by henriktao**
####
Enable configuration of CosmosDB optional property feedPollDelay.

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
@henriktao Thank you for the pull request. I can see you changed all the formatting of this file (likely your IDE did this automatically). This formatting doesn't match other files in the project and makes the review really hard (see the difference). Could you please revert to the original and then apply your changes keeping the formatting? Thank you.

**Comment by henriktao** [comment]
@mikhailshilkov Sorry, did not realize the formatting. I have reverted and pushed the new changes.

**Review by mikhailshilkov — APPROVED** [review]
LGTM, thank you for this change! Could you please add a short note to CHANGELOG.md?

**Comment by henriktao** [comment]
@mikhailshilkov Yes, however, I think the CHANGELOG.md is deprecated. The notice says Github Releases are used for this repository. I am not sure how Github Releases works, do you mind giving me some directions?

**Comment by mikhailshilkov** [comment]
Oh! You are right, I'm out of date. Please ignore :)

**Comment by mikhailshilkov** [comment]
@jkodroff Do you know why the build is stuck? Could you merge the PR when the build is green please?

**Comment by stack72** [comment]
Hi folks - sorry we didn't merge this! I will do so now and we will have it released in the next provider release which should be Friday 18th March

**Comment by henriktao** [comment]
@stack72 Hi Paul, do you have any updates on the status for the next provider release?

**Pull request merged**
