### PR TITLE
Update pulumi-terraform-bridge to v3.33.0 and pulumi/sdk to 3.44.2

### PR DESCRIPTION
**Pull request by thomas11**
The bulk of the changes is from pulumi/pulumi-terraform-bridge#612.

The PR is still a draft because I'd like to take a closer look at why many examples disappeared.

### CODE REVIEW

**Comment by danielrbradley** [comment]
For this branch:

```
Example conversion metrics:
	148 HCL examples failed to convert in all languages
	0 HCL examples were converted in at least one language but failed to convert to TypeScript
	0 HCL examples were converted in at least one language but failed to convert to Python
	0 HCL examples were converted in at least one language but failed to convert to Go
	0 HCL examples were converted in at least one language but failed to convert to C#
	29 entity document sections contained unexpected HCL code snippets. Examples will be converted, but may not display correctly in the registry, e.g. lacking tabs.
```

For master:

```
Example conversion metrics:
	58 HCL examples failed to convert in all languages
	0 HCL examples were converted in at least one language but failed to convert to TypeScript
	0 HCL examples were converted in at least one language but failed to convert to Python
	0 HCL examples were converted in at least one language but failed to convert to Go
	0 HCL examples were converted in at least one language but failed to convert to C#
	29 entity document sections contained unexpected HCL code snippets. Examples will be converted, but may not display correctly in the registry, e.g. lacking tabs.
```

So this is a step backwards in terms of coverage. Probably worth spending a little time going through individual errors to understand why they're failing.

**Comment by thomas11** [comment]
> For this branch:
> 
> ```
> Example conversion metrics:
> 	148 HCL examples failed to convert in all languages
> 	0 HCL examples were converted in at least one language but failed to convert to TypeScript
> 	0 HCL examples were converted in at least one language but failed to convert to Python
> 	0 HCL examples were converted in at least one language but failed to convert to Go
> 	0 HCL examples were converted in at least one language but failed to convert to C#
> 	29 entity document sections contained unexpected HCL code snippets. Examples will be converted, but may not display correctly in the registry, e.g. lacking tabs.
> ```
> 
> For master:
> 
> ```
> Example conversion metrics:
> 	58 HCL examples failed to convert in all languages
> 	0 HCL examples were converted in at least one language but failed to convert to TypeScript
> 	0 HCL examples were converted in at least one language but failed to convert to Python
> 	0 HCL examples were converted in at least one language but failed to convert to Go
> 	0 HCL examples were converted in at least one language but failed to convert to C#
> 	29 entity document sections contained unexpected HCL code snippets. Examples will be converted, but may not display correctly in the registry, e.g. lacking tabs.
> ```
> 
> So this is a step backwards in terms of coverage. Probably worth spending a little time going through individual errors to understand why they're failing.

Trying to narrow down the offending change in a crude binary search, I upgraded to versions somewhat in the middle between current and latest.
```
github.com/pulumi/pulumi-terraform-bridge/v3 v3.32.0
github.com/pulumi/pulumi/sdk/v3 v3.42.0
```
This preserves the example, so the change came later.

**Comment by thomas11** [comment]
```
rg --replace '$1' '^    \* failed to convert HCL for .* to .*?: (.*)$' build_master.log | sort | uniq -c
  10 Could not automatically download and install resource plugin 'pulumi-resource-local', install the plugin using `pulumi plugin install resource local`.
   1 invalid Go source code:
  60 panic converting HCL: fatal: A failure has occurred
  10 panic converting HCL: runtime error: invalid memory address or nil pointer dereference

rg --replace '$1' '^    \* failed to convert HCL for .* to .*?: (.*)$' build_upgrade.log | sort | uniq -c
  10 Could not automatically download and install resource plugin 'pulumi-resource-local', install the plugin using `pulumi plugin install resource local`.
   1 invalid Go source code:
  60 panic converting HCL: fatal: A failure has occurred
 940 panic converting HCL: runtime error: invalid memory address or nil pointer dereference
^^^^
```

**Comment by thomas11** [comment]
Confirmed via local experimentation that using a recent master of pulumi/pulumi brings the example conversion failures back down, thanks to pulumi/pulumi#11311. We need to upgrade terraform-bridge to use a version of pulumi that includes this fix.

**Comment by danielrbradley** [comment]
cc: @viveklak I think you mentioned you were investigating how to get the bridge upgrade unblocked. Let us know if there's anything we can do to aid the roll-out when it gets there

**Comment by thomas11** [comment]
closing in favor of a new PR with more recent versions

**Pull request closed without merging**
