### PR TITLE
Add a test for subnet

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Add a test to catch https://github.com/pulumi/pulumi/issues/3621

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
@stack72 Do we want to merge now and honestly fail the build, or do we wait until the bug is fixed?

**Comment by stack72** [comment]
🤷‍♂ I don't know :) I am happy you showed that it's currently broken though

**Comment by stack72** [comment]
@mikhailshilkov do we still need this?

**Comment by mikhailshilkov** [comment]
Yes, let me rebase

**Pull request merged**
