### PR TITLE
Upgrade terraform-provider-azurerm to v3.114.0

### LINKED ISSUE #2308: Upgrade terraform-provider-azurerm to v3.114.0
Release details: https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.114.0

### PR DESCRIPTION
**Pull request by thomas11**
This PR was generated via `$ upgrade-provider pulumi/pulumi-azure --kind=all --target-bridge-version=latest`.

After patches applied cleanly, it didn't build due to duplicate imports and did
- `upstream.sh checkout`
- edit
- commit
- `upstream.sh rebase -i`
- `upstream.sh check_in`

---

- Upgrading terraform-provider-azurerm from 3.113.0  to 3.114.0.
	Fixes #2308

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]

**Comment by danielrbradley** [comment]
Looks like the Java test failure is something to do with downloading the random provider. I think this might be related to a change in ci-mgmt which disables auto-download of plugins.

**Comment by iwahbe** [comment]
@thomas11 Looks like a java test failed with:
```
  Error: error resolving type of resource random: internal error loading package "random": Could not automatically download and install resource plugin 'pulumi-resource-random' at version v4.16.3, install the plugin using `pulumi plugin install resource random v4.16.3`: error downloading provider random to file: failed to download plugin: random-4.16.3: write /tmp/pulumi-plugin-tar2770403083: no space left on device
```

I retried.

**Comment by danielrbradley** [comment]
Oh, it's lack of disk space apparently

**Comment by iwahbe** [comment]
> Looks like the Java test failure is something to do with downloading the random provider. I think this might be related to a change in ci-mgmt which disables auto-download of plugins.

I'm skeptical, since this PR doesn't include that change. It does bump the version of Java used though...

**Comment by danielrbradley** [comment]
We should be able to set `freeDiskSpaceBeforeTest` in the ci-mgmt config:

https://github.com/pulumi/ci-mgmt/blob/3c3b89fcd146996cae678b5775f44ca81def5f71/provider-ci/internal/pkg/templates/bridged-provider.config.yaml#L69-L70

**Pull request merged**
